build:
  image: golang
  commands:
    - go get
    - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .
  when:
    event: push

publish:
  docker:
    username: allanks
    password: $$DOCKER_PASSWORD
    email: $$EMAIL
    repo: allanks/tas-job
    when:
      branch: master
      event: push

  ssh:
    host: docker-testbed
    user: root
    commands:
      - docker login -u allanks -p $$DOCKER_PASSWORD
      - docker pull allanks/tas-job
      - docker stop tas-job
      - docker rm tas-job
      - docker run --name tas-job -p 8080:8080 allanks/tas-job
    when:
      branch: master
      event: push