build:
  image: golang
  commands:
    - go get
    - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .
  when:
    event: push
publish:
  docker:
    username: $DOCKER_USER
    password: $DOCKER_PASSWORD
    email: $EMAIL
    repo: allanks/tas-job
    when:
      branch: master
      event: push